// Professional StockFlow AI Dashboard Report
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export interface DashboardReportData {
  period:string;
  summary:{
    total_products:number;
    total_categories:number;
    total_suppliers:number;
    total_customers:number;
    total_sales:number;
    total_purchases:number;
    low_stock_products:number;
    today_sales:number;
    today_purchases:number;
  };
  topProducts:{product:string;units_sold:number;revenue:number;}[];
  bestCustomers:{customer:string;orders:number;total_purchase:number;}[];
  recentSales:{id:number;customer:string;total:number;date:string;}[];
}

const money=(n:number)=>`Rs. ${n.toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2})}`;

export function exportDashboardReport(report:DashboardReportData){
 const pdf=new jsPDF();
 pdf.setFillColor(37,99,235);
 pdf.rect(0,0,210,30,"F");
 pdf.setTextColor(255);
 pdf.setFont("helvetica","bold");
 pdf.setFontSize(22);
 pdf.text("StockFlow AI",14,18);
 pdf.setFontSize(11);
 pdf.setFont("helvetica","normal");
 pdf.text("Inventory Dashboard Report",14,25);

 pdf.setTextColor(0);
 pdf.setFontSize(10);
 pdf.text(`Generated: ${new Date().toLocaleString()}`,14,40);
 pdf.text(`Period: ${report.period.toUpperCase()}`,14,46);

 autoTable(pdf,{
 startY:54,
 theme:"grid",
 head:[["Metric","Value"]],
 headStyles:{fillColor:[37,99,235]},
 alternateRowStyles:{fillColor:[245,247,250]},
 body:[
 ["Total Products",report.summary.total_products],
 ["Categories",report.summary.total_categories],
 ["Suppliers",report.summary.total_suppliers],
 ["Customers",report.summary.total_customers],
 ["Total Sales",money(report.summary.total_sales)],
 ["Total Purchases",money(report.summary.total_purchases)],
 ["Low Stock Products",report.summary.low_stock_products],
 ["Today's Sales",money(report.summary.today_sales)],
 ["Today's Purchases",money(report.summary.today_purchases)]
 ]});

 autoTable(pdf,{
 startY:(pdf as any).lastAutoTable?.finalY ? (pdf as any).lastAutoTable.finalY + 10 : 120,
 theme:"striped",
 head:[["Top Selling Product","Units","Revenue"]],
 headStyles:{fillColor:[37,99,235]},
 body:report.topProducts.length?report.topProducts.map(p=>[p.product,p.units_sold,money(p.revenue)]):[["No data","",""]]
 });

 autoTable(pdf,{
 startY:(pdf as any).lastAutoTable?.finalY ? (pdf as any).lastAutoTable.finalY + 10 : 170,
 theme:"striped",
 head:[["Customer","Orders","Purchase"]],
 headStyles:{fillColor:[37,99,235]},
 body:report.bestCustomers.length?report.bestCustomers.map(c=>[c.customer,c.orders,money(c.total_purchase)]):[["No data","",""]]
 });

 autoTable(pdf,{
 startY:(pdf as any).lastAutoTable?.finalY ? (pdf as any).lastAutoTable.finalY + 10 : 220,
 theme:"striped",
 head:[["Sale ID","Customer","Amount","Date"]],
 headStyles:{fillColor:[37,99,235]},
 body:report.recentSales.length?report.recentSales.map(s=>[s.id,s.customer,money(s.total),s.date]):[["No data","","",""]]
 });

 const pages=pdf.getNumberOfPages();
 for(let i=1;i<=pages;i++){
  pdf.setPage(i);
  pdf.line(14,286,196,286);
  pdf.setFontSize(9);
  pdf.setTextColor(120);
  pdf.text("Generated by StockFlow AI",14,292);
  pdf.text(`Page ${i} of ${pages}`,196,292,{align:"right"});
 }
 pdf.save(`Dashboard_Report_${new Date().toISOString().split("T")[0]}.pdf`);
}